### ISSUE TITLE
Migrate to Mezzio

### ISSUE THREAD

**Issue by Slamdunk** [Naktibalda/module-zendexpressive#1]
Hi, ZendExpressive moved to Mezzio.

I propose to declare this module as deprecated, copy-paste it into a new `module-mezzio` and just rename everything, exactly like what ZF dev team did.

What do you think?

**Comment by Naktibalda** [comment]
I copied this module to https://github.com/Codeception/module-mezzio , please update everything and raise pull request.

**Comment by Slamdunk** [comment]
Awesome, will do soon.

In the last commit of the new package https://github.com/Codeception/module-mezzio/commits/master I see no Travis build: have you enabled it, so I can have feedback from it within the Pull-Request?

**Comment by Naktibalda** [comment]
https://travis-ci.org/Codeception/module-mezzio

**Comment by Slamdunk** [comment]
https://travis-ci.org/Codeception/module-mezzio is now active and stable, this repository should be archived

**Comment by Naktibalda** [comment]
I added Mezzio module to website: https://codeception.com/docs/modules/Mezzio

https://codeception.com/docs/modules/ZendExpressive is a symlink to Mezzio page.

**Comment by Naktibalda** [comment]
And I'm going to archive this repo right now.
